# Generated by Django 5.2.11 on 2026-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('rnokpp', models.CharField(blank=True, max_length=15, verbose_name='РНОКПП (ІПН)')),
                ('kep_file', models.FileField(blank=True, null=True, upload_to='kep_certs/', verbose_name='Сертифікат КЕП')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Штатний розпис',
                'ordering': ['full_name'],
            },
        ),
    ]
