# Generated by Django 5.2.11 on 2026-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_employee_kep_file_kepcertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kepcertificate',
            name='file',
        ),
        migrations.AddField(
            model_name='kepcertificate',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригінальна назва'),
        ),
    ]
