# Generated by Django 5.2.11 on 2026-02-07 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_kepcertificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kepcertificate',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='kep_certs/', verbose_name='Файл сертифікату'),
            preserve_default=False,
        ),
    ]
