# Generated by Django 5.2.11 on 2026-02-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_kepcertificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата призначення'),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_order_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/appointment/', verbose_name='Скан наказу (PDF)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ Наказу про призначення'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата звільнення'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dismissal_order_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/dismissal/', verbose_name='Скан наказу про звільнення (PDF)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dismissal_order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ Наказу про звільнення'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='Звільнений'),
        ),
    ]
