# Generated by Django 5.2.11 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employee_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_order_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ориг. назва наказу про призначення'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dismissal_order_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ориг. назва наказу про звільнення'),
        ),
    ]
