# Generated by Django 5.2.11 on 2026-02-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_employee_appointment_order_original_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField(auto_now_add=True, verbose_name='Дата зміни')),
                ('previous_position', models.CharField(blank=True, max_length=100, verbose_name='Минула посада')),
                ('new_position', models.CharField(blank=True, max_length=100, verbose_name='Нова посада')),
                ('previous_department', models.CharField(blank=True, max_length=100, verbose_name='Минулий відділ')),
                ('new_department', models.CharField(blank=True, max_length=100, verbose_name='Новий відділ')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примітка (наприклад, № наказу)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='staff.employee', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Запис історії',
                'verbose_name_plural': 'Історія переміщень',
                'ordering': ['-date_changed'],
            },
        ),
    ]
