# Generated by Django 5.2.11 on 2026-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_todotask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoTask',
        ),
    ]
