# Generated by Django 5.2.11 on 2026-03-12 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_delete_todotask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerhistory',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон має бути у форматі: '+999999999'. Від 9 до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
