# Generated by Django 5.2.11 on 2026-03-12 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_careerhistory_notes_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_order_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ориг. назва наказу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissal_order_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/dismissal/', verbose_name='Скан наказу про звільнення'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон має бути у форматі: 000-000-00-00', regex='^\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
