# Generated by Django 5.2.11 on 2026-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва файлу')),
                ('doc_type', models.CharField(choices=[('driver', 'Драйвер / Програма'), ('instruction', 'Інструкція'), ('template', 'Шаблон документу'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлове сховище',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
