# Generated by Django 5.2.11 on 2026-02-06 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('refill', 'Заправка картриджа'), ('repair', 'Ремонт техніки')], default='refill', max_length=20, verbose_name='Тип роботи')),
                ('device_name', models.CharField(max_length=200, verbose_name='Назва картриджа/принтера')),
                ('requester_name', models.CharField(max_length=100, verbose_name='ПІБ (хто дав)')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ/Кабінет')),
                ('date_received', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отримання')),
                ('date_sent', models.DateField(blank=True, null=True, verbose_name='Дата відправки сервісу')),
                ('date_returned', models.DateField(blank=True, null=True, verbose_name='Дата повернення')),
                ('description', models.TextField(blank=True, verbose_name='Опис проблеми/робіт')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка в сервіс',
                'verbose_name_plural': 'Журнал ремонтів та заправок',
                'ordering': ['-date_received'],
            },
        ),
    ]
