# Generated by Django 5.2.11 on 2026-02-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicetask_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetask',
            name='asset',
        ),
    ]
