# Generated by Django 5.2.11 on 2026-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_servicetask_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('tasks', models.ManyToManyField(related_name='reports', to='service.servicetask', verbose_name='Картриджі у звіті')),
            ],
            options={
                'verbose_name': 'Збережений акт',
                'verbose_name_plural': 'Історія роздруківок',
                'ordering': ['-created_at'],
            },
        ),
    ]
