# Generated by Django 5.2.11 on 2026-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='date_back_from_service',
            field=models.DateField(blank=True, null=True, verbose_name='Повернуто з сервісу'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Дата повернення клієнту'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправки'),
        ),
    ]
