# Generated by Django 5.2.11 on 2026-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicetask_date_back_from_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='task_type',
            field=models.CharField(choices=[('refill', 'Заправка картриджа'), ('repair', 'Ремонт техніки'), ('drum_clean', 'Чистка драм-юніта')], default='refill', max_length=20, verbose_name='Тип робіт'),
        ),
    ]
