# Generated by Django 5.2.11 on 2026-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicetask_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicetask',
            options={},
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='tasks',
            field=models.ManyToManyField(to='service.servicetask', verbose_name='Картриджі в акті'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Відділ'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис проблеми'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='device_name',
            field=models.CharField(max_length=200, verbose_name='Назва пристрою/Картриджу'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='requester_name',
            field=models.CharField(max_length=100, verbose_name='Замовник (ПІБ)'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='task_type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('refill', 'Заправка'), ('maintenance', 'Обслуговування'), ('drum_clean', 'Чистка драм-юніта')], default='refill', max_length=20, verbose_name='Тип робіт'),
        ),
    ]
