# Generated by Django 5.2.11 on 2026-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicetaskitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetaskitem',
            name='item_name',
            field=models.CharField(choices=[('Картридж Xerox Phaser 3020, WC3025', 'Картридж Xerox Phaser 3020, WC3025'), ('Картридж Canon 725/ HP [CE285A]', 'Картридж Canon 725/ HP [CE285A]'), ('Тонер-картридж OKI MB472', 'Тонер-картридж OKI MB472'), ('Картридж HP [CF283A]', 'Картридж HP [CF283A]'), ('Картридж Canon 103/303/703/HP [Q2612A]', 'Картридж Canon 103/303/703/HP [Q2612A]'), ('Картридж HP [CE278A]', 'Картридж HP [CE278A]'), ('Картридж Canon FX-10', 'Картридж Canon FX-10'), ('Картридж Canon 728', 'Картридж Canon 728'), ('Картридж HP [Q7553A]', 'Картридж HP [Q7553A]'), ('Картридж Samsung MLT-D101S', 'Картридж Samsung MLT-D101S'), ('Картридж Canon 712/ HP [CB435A]', 'Картридж Canon 712/ HP [CB435A]'), ('Картридж HP [CE505A]', 'Картридж HP [CE505A]'), ('Картридж HP [CB436A]', 'Картридж HP [CB436A]'), ('Барабан OKI', 'Барабан OKI'), ('Інше', 'Інше (вказати вручну)')], max_length=100, verbose_name='Тип картриджа/пристрою'),
        ),
    ]
