# Generated by Django 5.2.11 on 2026-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_servicetaskitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskitem',
            name='date_back_from_service',
            field=models.DateField(blank=True, null=True, verbose_name='Повернувся з сервісу'),
        ),
        migrations.AddField(
            model_name='servicetaskitem',
            name='date_returned_to_user',
            field=models.DateField(blank=True, null=True, verbose_name='Видано клієнту'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_back_from_service',
            field=models.DateField(blank=True, null=True, verbose_name='Повернуто з сервісу (Загальне)'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закриття заявки'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправки (Акт)'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва пристрою/Картриджу'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='requester_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Замовник (ПІБ)'),
        ),
    ]
