# Generated by Django 5.2.11 on 2026-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_servicetaskitem_date_back_from_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примітка до позиції'),
        ),
    ]
