# Generated by Django 5.2.11 on 2026-02-20 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_servicetaskitem_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaskitem',
            name='note',
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
