# Generated by Django 5.2.11 on 2026-02-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_servicetaskitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примітка до позиції'),
        ),
    ]
