# Generated by Django 5.2.11 on 2026-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_servicetaskitem_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereport',
            options={'ordering': ['-id'], 'verbose_name': 'Акти', 'verbose_name_plural': 'Акти'},
        ),
        migrations.AlterModelOptions(
            name='servicetask',
            options={'ordering': ['-id'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='servicetaskitem',
            options={'ordering': ['-id'], 'verbose_name': 'Картриджі', 'verbose_name_plural': 'Картриджі на заправку'},
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='date_back_from_service',
            field=models.DateField(blank=True, null=True, verbose_name='Повернуто з сервісу'),
        ),
    ]
