# Generated by Django 5.2.11 on 2026-02-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва майна')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Інвентарний номер')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Баркод')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='Матеріально відповідальний')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Кабінет/Локація')),
                ('account', models.CharField(choices=[('104', 'Рахунок 104 (Основні засоби)'), ('113', 'Рахунок 113 (Малоцінні)')], max_length=3, verbose_name='Рахунок')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє редагування')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Майно',
                'verbose_name_plural': 'Список майна',
                'ordering': ['-created_at'],
            },
        ),
    ]
