# Generated by Django 5.2.11 on 2026-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='archive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата архівування'),
        ),
        migrations.AddField(
            model_name='asset',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина архівування (кому передано/списання)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архіві'),
        ),
    ]
