# Generated by Django 5.2.11 on 2026-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_archive_date_asset_archive_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.TextField(verbose_name='Назва майна'),
        ),
    ]
