# Generated by Django 5.2.11 on 2026-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, choices=[('100', '100'), ('504', '504')], default='100', max_length=100, verbose_name='Кабінет/Локація'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='responsible_person',
            field=models.CharField(choices=[('Костишин О.В.', 'Костишин О.В.'), ('Олійник М.Р.', 'Олійник М.Р.')], default='Костишин О.В.', max_length=100, verbose_name='Матеріально відповідальний'),
        ),
    ]
