# Generated by Django 5.2.11 on 2026-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Підрозділ / Відділ')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код відділу')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ Працівника/Керівника')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('ip_phone', models.CharField(blank=True, max_length=20, verbose_name='IP телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, verbose_name='Мобільний')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Запис довідника',
                'verbose_name_plural': 'Телефонний довідник',
                'ordering': ['department', 'full_name'],
            },
        ),
    ]
