# Generated by Django 5.2.11 on 2026-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebookentry',
            options={'ordering': ['department'], 'verbose_name': 'Запис довідника', 'verbose_name_plural': 'Телефонний довідник'},
        ),
        migrations.RemoveField(
            model_name='phonebookentry',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='phonebookentry',
            name='ip_phone',
        ),
        migrations.RemoveField(
            model_name='phonebookentry',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='phonebookentry',
            name='position',
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='chief_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP телефон начальника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='chief_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ПІБ Начальника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='chief_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мобільний начальника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='chief_position',
            field=models.CharField(default='Начальник відділу', max_length=100, verbose_name='Посада керівника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='deputy_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP телефон заступника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='deputy_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ПІБ Заступника'),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='deputy_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мобільний заступника'),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Загальний Email'),
        ),
    ]
