# Generated by Django 5.2.11 on 2026-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_phonebookentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookentry',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Коди відділів'),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='department',
            field=models.TextField(verbose_name='Підрозділи / Відділи'),
        ),
    ]
