# Generated by Django 5.2.11 on 2026-02-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_phonebookentry_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebookentry',
            options={'ordering': ['code', 'department'], 'verbose_name': 'Запис довідника', 'verbose_name_plural': 'Телефонний довідник'},
        ),
    ]
